name: Matter Validation

on:
  pull_request:
   branches:
     - main
     - 'v*-branch'

   paths:
     - 'samples/matter/**'
     - 'applications/matter_bridge/**'
     - 'applications/matter_weather_station/**'

permissions:
  contents: read

jobs:
  matter-validation:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          path: ncs/nrf
      
      - name: Rebase
        if: github.event_name == 'pull_request'
        continue-on-error: true
        env:
          BASE_REF: ${{ github.base_ref }}
          PR_HEAD: ${{ github.event.pull_request.head.sha }}
        working-directory: ncs/nrf
        run: |
          git config --global user.email "actions@zephyrproject.org"
          git config --global user.name "Github Actions"
          rm -fr ".git/rebase-apply"
          rm -fr ".git/rebase-merge"
          git rebase origin/${BASE_REF}
          git clean -f -d
          git log --graph --oneline HEAD...${PR_HEAD}

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: ncs/nrf/scripts/requirements.txt

      - name: Install packages
        working-directory: ncs/nrf
        run: |
          sudo apt update
          sudo apt-get install -y wget python3-pip git
          pip install -r scripts/requirements.txt

      - name: Checkout Matter repository
        working-directory: ncs
        run: |
          git clone https://github.com/nrfconnect/sdk-connectedhomeip modules/lib/matter
          cd modules/lib/matter
          git checkout master 

      - name: validate Matter samples and documentation
        working-directory: ncs
        run: |
          python nrf/scripts/matter/matter_sample_checker/matter_sample_checker.py --samples-zap-yaml nrf/samples/matter/common/src/zap_samples.yml --base nrf
